Targetting fullest storage
BWeesy/Screeps pull request #24
Opened 2022-08-05 16:24 UTC by nicmictho

closes #23

2022-08-05 16:38 UTC, BWeesy requested changes

2022-08-05 16:38 UTC, BWeesy commented on src/role/hauler.js
> +                console.log(targetter.withdraw(creep))
Remove logs pls

2022-08-05 16:38 UTC, BWeesy commented on src/utils/spawning.js
>      while(cost + body.WORK.cost + body.CARRY.cost <= availableEnergy){
Update cost in this loop to match what's in the loop pls.

2022-08-05 16:38 UTC, BWeesy commented on src/utils/targetting.js
> +            targetStorage = _.sortBy(targets, t => t.store[RESOURCE_ENERGY])[targets.length -1];
Please use lodash last.
https://lodash.com/docs/4.17.15#last

2022-08-06 10:42 UTC, nicmictho commented
also closes #25

2022-08-06 16:28 UTC, BWeesy approved these changes

2022-08-06 16:30 UTC, merged